
export enum ROLE {
    CUSTOMER = 'CUSTOMER',
    VENDOR = 'VENDOR',
    ADMIN = 'ADMIN',
}

export enum DELIVERY_STATUS {
    CANCELLED = 'CANCELLED',
    PENDING = 'PENDING',
    COMPLETED = 'COMPLETED',
}

export enum DELIVERY_RECIPIENT_STATUS {
    CANCELLED = 'CANCELLED',
    PENDING = 'PENDING',
    RIDER_ACCEPTED = 'RIDER_ACCEPTED',
    PICKED_UP = 'PICKED_UP',
    DELIVERING = 'DELIVERING',
    DELIVERED = 'DELIVERED',
}

export enum DELIVERY_RIDER_REQUEST_STATUS {
    DECLINED = 'DECLINED',
    PENDING = 'PENDING',
    ACCEPTED = 'ACCEPTED',
}